### PR TITLE
Fix[Home_page]: Resolved navbar file path

### PR DESCRIPTION
**Pull request by domisplaying**
- Corrected the navbar file path

### CODE REVIEW

**Comment by Dumbaiman** [comment]
thanks bro

**Comment by t0tally-pr0fessional** [comment]
good to see bug fixed

**Review by 67Izac — APPROVED** [review]
looks good...couldn't  believe we missed this error the last time

**Review by Abdillah31X — APPROVED** [review]
nice well done

**Review by Dumbaiman — COMMENTED** [review]
nice

**Pull request merged**
